package io.onloopio;
import android.test.*;
import android.database.sqlite.SQLiteDatabase;
import io.onloopio.db.*;
import io.onloopio.model.*;
import io.onloopio.player.*;
import io.onloopio.api.*;
import java.util.*;
import java.io.*;
/** Runs on real API17 SQLite with only disposable private DBs and synthetic metadata. */
public final class RuntimeStoreTest extends InstrumentationTestCase {
    private MetadataStore store;private RenamingDelegatingContext context;private String prefix;
    protected void setUp()throws Exception{super.setUp();prefix="runtime_"+System.nanoTime()+"_";context=new RenamingDelegatingContext(getInstrumentation().getTargetContext(),prefix);store=new MetadataStore(context);store.selectAccount("fixture");}
    protected void tearDown()throws Exception{store.close();getInstrumentation().getTargetContext().deleteDatabase(prefix+"onloopio.db");super.tearDown();}
    private Song song(String id){return new Song(id,"Title "+id,"Artist","Album","mp3",600);}
    private PlaybackQueue queue(){PlaybackQueue q=new PlaybackQueue(new Random(9));q.replace(Arrays.asList(new PlaybackQueue.Entry("one","fixture",song("A")),new PlaybackQueue.Entry("two","fixture",song("A")),new PlaybackQueue.Entry("three","fixture",song("B"))),0);return q;}
    public void testSessionCheckpointAndQualificationAfterAck(){PlaybackQueue q=queue();q.configure(true,0);q.next(false);ListeningSession l=new ListeningSession();l.restore(240000,true,2);new SessionStore(store).save(q,"attempt",123,l,220000,true);ListenEvent event=new ListenEvent("attempt","fixture","A",123);store.recordListening(event,500);store.acknowledgeListens(Arrays.asList(event));store.recordListening(event,600);assertEquals(1,store.audioState("A").plays);assertEquals(0,store.pendingFeedback("fixture"));SessionStore.Restored r=new SessionStore(store).load();assertEquals(q.current().id,r.queue.current().id);assertEquals(220000,r.position);assertTrue(r.qualified);assertEquals(q.peek(true).id,r.queue.peek(true).id);assertTrue(store.protectedFromCleanup("B"));assertEquals(1,new FeedbackStore(store).history("fixture",0).size());store.selectAccount("other");assertEquals("fixture",new SessionStore(store).load().queue.current().account);assertFalse(store.protectedFromCleanup("B"));}
    public void testLocalDedupSurvivesAck(){ListenEvent event=new ListenEvent("local-attempt","","local:A",1000);store.recordListening(event,2000);store.recordListening(event,3000);assertEquals(1,store.audioState("local:A").plays);assertEquals(0,store.pendingFeedback("fixture"));}
    public void testDelayedQualificationRetainsOriginalAccount(){store.selectAccount("other");store.recordListening(new ListenEvent("old-owner","fixture","A",100),200);assertEquals(1,store.pendingFeedback("fixture"));assertEquals(0,store.pendingFeedback("other"));assertEquals(0,store.audioState("A").plays);assertEquals(1,new FeedbackStore(store).history("fixture",0).size());}
    private PlaylistDetail detail(String rev,String... ids){List<Song> songs=new ArrayList<Song>();for(String id:ids)songs.add(song(id));return new PlaylistDetail(new Playlist("mix","Mix",rev,songs.size(),600),songs);}
    public void testWholeGenerationActivationV1V2V3AndReconcile(){GenerationStore generations=new GenerationStore(store);generations.stage("fixture",detail("v1","A","B","A"));generations.reconcile("fixture",Arrays.asList(CacheKey.audioName("A"),CacheKey.audioName("B")),100);assertEquals(3,generations.summary("fixture","mix").ready);assertEquals(2,generations.summary("fixture","mix").unique);generations.stage("fixture",detail("v2","A","C"));generations.reconcile("fixture",Arrays.asList(CacheKey.audioName("A"),CacheKey.audioName("B")),200);assertEquals("B",generations.active("fixture","mix").songs.get(1).id);assertTrue(store.protectedFromCleanup("B"));generations.stage("fixture",detail("v3","A","D"));generations.reconcile("fixture",Arrays.asList(CacheKey.audioName("A"),CacheKey.audioName("B"),CacheKey.audioName("C")),300);assertEquals("B",generations.active("fixture","mix").songs.get(1).id);generations.reconcile("fixture",Arrays.asList(CacheKey.audioName("A"),CacheKey.audioName("D")),400);assertEquals("D",generations.active("fixture","mix").songs.get(1).id);assertFalse(store.protectedFromCleanup("B"));generations.reconcile("fixture",Arrays.asList(CacheKey.audioName("A")),500);assertTrue(generations.summary("fixture","mix").degraded);generations.detached("fixture","mix");assertTrue(generations.summary("fixture","mix").detached);}
    public void testFeedbackBackoffAndPoisonIsolation(){ListenEvent a=new ListenEvent("a","fixture","A",100),b=new ListenEvent("b","fixture","B",101);store.recordListening(a,200);store.recordListening(b,201);store.failedListen(a,new ApiException(70));assertEquals(1,store.pendingListens("fixture",10).size());assertEquals("b",store.pendingListens("fixture",10).get(0).sessionId);new FeedbackStore(store).retry("fixture");assertEquals(2,store.pendingListens("fixture",10).size());}
    public void testClockConfidenceSurvivesCheckpointAndAck(){long wall=1700000000000L;ListeningSession listening=new ListeningSession();listening.observeClock(wall,1000);SessionStore sessions=new SessionStore(store);sessions.save(queue(),"clock-attempt",wall,listening,0,true);assertFalse(sessions.load().clockUncertain);listening.observeClock(wall-3600000,2000);sessions.save(queue(),"clock-attempt",wall,listening,1000,false,false);SessionStore.Restored restored=sessions.load();assertTrue(restored.clockUncertain);assertEquals(wall,restored.started);ListenEvent event=new ListenEvent("clock-attempt","fixture","A",wall);store.recordListening(event,wall+300000,true);store.acknowledgeListens(Arrays.asList(event));assertTrue(new FeedbackStore(store).history("fixture",0).get(0).clockUncertain);assertEquals(wall,new FeedbackStore(store).history("fixture",0).get(0).started);assertEquals(1,store.audioState("A").plays);}
    public void testRetryClockRollbackDoesNotWaitYears(){long now=System.currentTimeMillis();ListenEvent event=new ListenEvent("clock-retry","fixture","A",now);store.recordListening(event,now);FeedbackStore feedback=new FeedbackStore(store);feedback.failure("fixture","listen",event.sessionId,0,new IOException(),now);assertEquals(0,store.pendingListens("fixture",10).size());feedback.failure("fixture","listen",event.sessionId,0,new IOException(),now+365L*86400000);assertEquals(1,store.pendingListens("fixture",10).size());feedback.failure("fixture","listen",event.sessionId,0,new ApiException(70),now+365L*86400000);assertEquals(0,store.pendingListens("fixture",10).size());feedback.retry("fixture");assertEquals(1,store.pendingListens("fixture",10).size());}
    public void testHistoryPruningProtectsPendingCurrentAndLedger(){long now=System.currentTimeMillis(),old=now-100L*86400000;ListeningSession listen=new ListeningSession();listen.observeClock(now,1000);new SessionStore(store).save(queue(),"current-old",old,listen,0,true);ListenEvent pending=new ListenEvent("pending-old","fixture","A",old),delivered=new ListenEvent("delivered-old","fixture","A",old);store.recordListening(pending,now);store.recordListening(delivered,now);store.acknowledgeListens(Arrays.asList(delivered));new FeedbackStore(store).prune(now);assertEquals(2,new FeedbackStore(store).history("fixture",0).size());assertEquals(1,store.pendingFeedback("fixture"));assertEquals("current-old",new SessionStore(store).load().attempt);store.recordListening(delivered,now+1);assertEquals(2,store.audioState("A").plays);assertEquals(2,new FeedbackStore(store).history("fixture",0).size());new SessionStore(store).clear();listen.reset();listen.observeClock(now,2000);new SessionStore(store).save(queue(),"fresh-local-history",now,listen,0,true);assertEquals(2,new FeedbackStore(store).history("fixture",0).size());assertEquals(0,android.database.DatabaseUtils.longForQuery(store.getReadableDatabase(),"SELECT COUNT(*) FROM listen_history WHERE attempt_id='current-old'",null));}
    public void testGainJsonAndOfflineStorage()throws Exception{ReplayGain gain=NavidromeClient.parseReplayGain("{\"subsonic-response\":{\"status\":\"ok\",\"song\":{\"id\":\"A\",\"replayGain\":{\"trackGain\":-6.0,\"albumGain\":0,\"trackPeak\":1}}}}".getBytes("UTF-8"),"A");assertEquals(-6.0,gain.track,0.001);assertEquals(0.0,gain.album,0.001);new GainStore(store).save("fixture","A",gain);assertEquals(gain.volume(1,0,0,false),new GainStore(store).load("fixture","A").volume(1,0,0,false),0.0001);}
    public void testGainArtifactStampAndNormalizationIsolation()throws Exception{File file=File.createTempFile("gain-source",".wav",getInstrumentation().getTargetContext().getFilesDir());try{FileOutputStream out=new FileOutputStream(file);out.write(new byte[64]);out.close();ReplayGain gain=new ReplayGain(-6.0,null,1.0,null,null,null);GainStore gains=new GainStore(store);gains.saveArtifact("fixture","original",file,gain,false);gains.saveArtifact("fixture","compact",file,gain,true);assertEquals(-6.0,gains.artifact("fixture","original",file).track,0.001);assertNull(gains.artifact("fixture","compact",file).track);out=new FileOutputStream(file,true);out.write(0);out.close();assertNull(gains.artifact("fixture","original",file).track);gains.saveLocal("local:test",file,gain);assertTrue(gains.hasLocal("local:test",file));assertEquals(-6.0,gains.local("local:test",file).track,0.001);}finally{file.delete();}}
    public void testBaselineAndSequentialMigrations()throws Exception{migration(false);migration(true);}
    public void testVersion19ArtifactsAndPartialsSurviveVersion20()throws Exception{SQLiteDatabase db=SQLiteDatabase.create(null);try{BufferedReader reader=new BufferedReader(new InputStreamReader(getInstrumentation().getContext().getAssets().open("baseline-v9.sql"),"UTF-8"));try{String line;while((line=reader.readLine())!=null)if(line.trim().length()>0)db.execSQL(line);}finally{reader.close();}store.onUpgrade(db,9,19);db.execSQL("INSERT INTO audio_partial(account,token,validator,offset,total) VALUES('fixture','original','\"v1\"',512,1024)");db.execSQL("INSERT INTO audio_artifact(account,token,song_id,profile,actual,bytes) VALUES('fixture','original','A',1,'flac',1024)");store.onUpgrade(db,19,20);assertEquals(512,android.database.DatabaseUtils.longForQuery(db,"SELECT offset FROM audio_partial",null));assertEquals(0,android.database.DatabaseUtils.longForQuery(db,"SELECT updated_at FROM audio_partial",null));assertEquals(1024,android.database.DatabaseUtils.longForQuery(db,"SELECT bytes FROM audio_artifact",null));assertEquals(0,android.database.DatabaseUtils.longForQuery(db,"SELECT bitrate+duration_ms FROM audio_artifact",null));}finally{db.close();}}
    public void testTenThousandEntriesAndProgressCheckpoint()throws Exception{
        List<PlaybackQueue.Entry> entries=new ArrayList<PlaybackQueue.Entry>();List<Song> songs=new ArrayList<Song>();List<String> tokens=new ArrayList<String>();
        for(int n=0;n<10000;n++){Song s=song("large-"+n);songs.add(s);entries.add(new PlaybackQueue.Entry("entry-"+n,"fixture",s));tokens.add(CacheKey.audioName(s.id));}
        PlaybackQueue q=new PlaybackQueue(new Random(17));q.replace(entries,0);q.configure(true,0);ListeningSession listen=new ListeningSession();SessionStore sessions=new SessionStore(store);
        long start=android.os.SystemClock.elapsedRealtime();sessions.save(q,"large-attempt",100,listen,1000,true);long full=android.os.SystemClock.elapsedRealtime()-start;
        start=android.os.SystemClock.elapsedRealtime();sessions.save(q,"large-attempt",100,listen,11000,false,false);long progress=android.os.SystemClock.elapsedRealtime()-start;
        assertEquals(10000,sessions.load().queue.entries().size());assertEquals(11000,sessions.load().position);
        GenerationStore generations=new GenerationStore(store);start=android.os.SystemClock.elapsedRealtime();generations.stage("fixture",new PlaylistDetail(new Playlist("large","Large","v1",10000,0),songs));generations.reconcile("fixture",tokens,100);long ready=android.os.SystemClock.elapsedRealtime()-start;
        assertEquals(10000,generations.summary("fixture","large").ready);assertEquals(10000,generations.summary("fixture","large").unique);
        android.os.Bundle measurements=new android.os.Bundle();measurements.putString("stream","10k full_checkpoint_ms="+full+" progress_checkpoint_ms="+progress+" stage_reconcile_ms="+ready+"\n");getInstrumentation().sendStatus(0,measurements);
    }
    public void testGainJsonRejectsDeepInput()throws Exception{StringBuilder nested=new StringBuilder();for(int n=0;n<40;n++)nested.append('[');for(int n=0;n<40;n++)nested.append(']');try{NavidromeClient.parseReplayGain(nested.toString().getBytes("UTF-8"),"A");fail("Depth bound");}catch(IOException expected){assertTrue(expected.getMessage().contains("depth"));}}
    private void migration(boolean sequential)throws Exception{
        String p="upgrade_"+System.nanoTime()+"_";RenamingDelegatingContext isolated=new RenamingDelegatingContext(getInstrumentation().getTargetContext(),p);File path=isolated.getDatabasePath("onloopio.db");path.getParentFile().mkdirs();SQLiteDatabase db=SQLiteDatabase.openOrCreateDatabase(path,null);
        BufferedReader reader=new BufferedReader(new InputStreamReader(getInstrumentation().getContext().getAssets().open("baseline-v9.sql"),"UTF-8"));try{String line;while((line=reader.readLine())!=null)if(line.trim().length()>0)db.execSQL(line);}finally{reader.close();}
        db.execSQL("INSERT INTO server(id,account_key) VALUES(1,'fixture')");db.execSQL("INSERT INTO listen_event VALUES('old-attempt','fixture','A',100)");db.execSQL("INSERT INTO audio_state(song_id,play_count,pinned) VALUES('A',7,1)");db.execSQL("INSERT INTO download_queue(song_id,position) VALUES('A',0)");db.setVersion(9);
        if(sequential){for(int v=9;v<20;v++){store.onUpgrade(db,v,v+1);db.setVersion(v+1);if(v==10){db.execSQL("INSERT INTO offline_generation(id,account,playlist_id,signature,name,activated) VALUES('legacy-gen','fixture','legacy-mix','old','Legacy',123)");db.execSQL("INSERT INTO offline_pointer(account,playlist_id,active) VALUES('fixture','legacy-mix','legacy-gen')");for(int n=0;n<3;n++)db.execSQL("INSERT INTO offline_member(generation,position,song_id,token,metadata,ready) VALUES(?,?,?,?,?,?)",new Object[]{"legacy-gen",n,n==1?"B":"A",CacheKey.audioName(n==1?"B":"A"),SessionStore.encodeSong(song(n==1?"B":"A")),n==1?0:1});}}}db.close();isolated.makeExistingFilesAndDbsAccessible();MetadataStore upgraded=new MetadataStore(isolated);try{assertEquals(20,upgraded.getReadableDatabase().getVersion());assertEquals(1,android.database.DatabaseUtils.longForQuery(upgraded.getReadableDatabase(),"SELECT clock_uncertain FROM attempt_ledger WHERE attempt_id='old-attempt'",null));assertEquals(7,upgraded.audioState("A").plays);assertTrue(upgraded.audioState("A").pinned);assertEquals(1,upgraded.pendingDownloads());assertEquals(1,upgraded.pendingListens("fixture",10).size());upgraded.recordListening(new ListenEvent("old-attempt","fixture","A",100),500);assertEquals(7,upgraded.audioState("A").plays);assertNull(new SessionStore(upgraded).load());if(sequential){GenerationStore.Summary legacy=new GenerationStore(upgraded).summary("fixture","legacy-mix");assertTrue(legacy.active);assertEquals(3,legacy.required);assertEquals(2,legacy.ready);assertEquals(1,legacy.unique);assertEquals(1200L,legacy.seconds);assertEquals(123L,legacy.activated);assertTrue(legacy.degraded);}}finally{upgraded.close();getInstrumentation().getTargetContext().deleteDatabase(p+"onloopio.db");}
    }
}
