plugins { id 'com.android.application' }
android {
    namespace 'io.onloopio'
    testNamespace 'io.onloopio.tests'
    compileSdk 35
    defaultConfig {
        applicationId 'io.onloopio'
        minSdk 17
        targetSdk 17
        versionCode 17
        versionName '0.10.1'
        testInstrumentationRunner 'io.onloopio.OnLoopioTestRunner'
        testApplicationId 'io.onloopio.tests'
        ndk { abiFilters 'armeabi-v7a' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        debug { debuggable true }
        release { debuggable false; minifyEnabled false }
    }
    lint { disable 'ExpiredTargetSdkVersion', 'OldTargetApi' }
    sourceSets { test.java.srcDir rootProject.file('tests') }
}
dependencies {
    implementation 'org.conscrypt:conscrypt-android:2.5.2'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'net.sf.kxml:kxml2:2.3.0'
    androidTestCompileOnly files("${android.sdkDirectory}/platforms/android-${android.compileSdk}/optional/android.test.base.jar",
        "${android.sdkDirectory}/platforms/android-${android.compileSdk}/optional/android.test.runner.jar",
        "${android.sdkDirectory}/platforms/android-${android.compileSdk}/optional/android.test.mock.jar")
}
