import io.onloopio.sync.*;
import io.onloopio.player.*;
import io.onloopio.api.*;
import org.junit.Test;
import static org.junit.Assert.*;
public final class PolicyAudioTest {
    @Test public void gateTable(){for(WorkPolicy.Work work:WorkPolicy.Work.values())for(int mask=0;mask<128;mask++){WorkPolicy.Input i=new WorkPolicy.Input();i.offline=(mask&1)!=0;i.usb=(mask&2)!=0;i.home=(mask&4)!=0;i.charging=(mask&8)!=0;i.low=(mask&16)!=0;i.manual=(mask&32)!=0;i.chargeProfile=(mask&64)!=0;i.battery=70;String reason=WorkPolicy.reason(i,work);if(i.offline || i.usb || !i.home)assertFalse(reason.isEmpty());if(i.manual && !i.offline && !i.usb && i.home && !i.low)assertEquals("",reason);}}
    @Test public void hysteresisAndRetry(){boolean low=false;for(int b:new int[]{20,21,24}){low=WorkPolicy.low(low,b);assertTrue(low);}assertFalse(WorkPolicy.low(low,25));assertEquals(60000,FeedbackRetry.delay(1));assertEquals(3600000,FeedbackRetry.delay(99));assertEquals("account",FeedbackRetry.kind(new ApiException(40)));assertEquals("quarantined",FeedbackRetry.kind(new ApiException(70)));assertEquals("transient",FeedbackRetry.kind(new java.io.IOException("permanent error")));assertEquals(3615000,WorkPolicy.boundedNext(0,Long.MAX_VALUE));}
    @Test public void signedGainsAndHeadroom(){assertEquals(.501187f,new ReplayGain(-6.0,null,null,null,null,null).volume(1,0,0,false),.00001f);assertEquals(1,new ReplayGain(6.0,null,null,null,null,null).volume(1,0,0,false),0);assertEquals(.5,new ReplayGain(0.0,null,2.0,null,null,null).volume(1,0,0,false),0);assertEquals(1,new ReplayGain(-6.0,null,null,null,null,null).volume(0,0,0,false),0);assertEquals(.501187f,new ReplayGain(null,null,null,null,null,-6.0).volume(2,0,0,false),.00001f);assertNull(new ReplayGain(Double.NaN,Double.POSITIVE_INFINITY,0.0,-1.0,null,null).track);assertTrue(new ReplayGain(0.0,null,null,null,null,null).volume(1,0,15,false)<.18f);}
    @Test public void variantsAndRanges()throws Exception{assertNotEquals(AudioProfile.token("s",0),AudioProfile.token("s",1));assertNotEquals(AudioProfile.token("s",1),AudioProfile.token("s",2));assertFalse(ResumableDownload.strong("W/\"etag\""));assertTrue(ResumableDownload.strong("\"etag\""));assertEquals(100,ResumableDownload.rangeTotal("bytes 50-99/100",50,50));try{ResumableDownload.rangeTotal("bytes 0-49/100",50,50);fail();}catch(java.io.IOException expected){}}
    @Test public void normalizedSourceKeepsEqHeadroom(){ReplayGain gain=new ReplayGain(-12.0,null,2.0,null,null,null);assertEquals(1,gain.volume(1,6,0,true),0);assertEquals(.501187f,gain.volume(1,6,6,true),.00001f);assertEquals(1,gain.volume(0,6,6,true),0);}
}
