import io.onloopio.api.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.net.*;
import java.util.*;
public final class RangeTransferTest {
    @Test public void truncatedOriginalResumesAnd200Restarts()throws Exception{for(final boolean ranges:new boolean[]{true,false}){
        final byte[] audio=new byte[4096];new Random(1).nextBytes(audio);final int[] requests={0};final boolean[] sawRange={false};HttpFixture server=new HttpFixture(new InetSocketAddress("127.0.0.1",0));server.createContext("/",new HttpFixture.Handler(){public void handle(HttpFixture.Exchange e)throws IOException{int request=++requests[0];String range=e.getRequestHeaders().values.get("range");sawRange[0]|=range!=null;e.getResponseHeaders().set("ETag","\"one\"");e.getResponseHeaders().set("Content-Type","audio/mpeg");int offset=range==null || !ranges?0:1024;if(offset>0)e.getResponseHeaders().set("Content-Range","bytes 1024-4095/4096");e.sendResponseHeaders(offset>0?206:200,4096-offset);e.getResponseBody().write(audio,offset,request==1?1024:4096-offset);}});server.start();File file=File.createTempFile("range",".part");final ResumableDownload.State state=new ResumableDownload.State();ResumableDownload.Journal journal=new ResumableDownload.Journal(){public void save(ResumableDownload.State value){assertTrue(value.offset<=file.length());}};final URL url=new URL("http://127.0.0.1:"+server.getAddress().getPort()+"/");ResumableDownload.Source source=new ResumableDownload.Source(){public HttpURLConnection open()throws IOException{return (HttpURLConnection)url.openConnection();}};
        try{try{ResumableDownload.transfer(source,file,4096,state,journal,null);fail();}catch(IOException expected){}assertEquals(1024,state.offset);ResumableDownload.transfer(source,file,4096,state,journal,null);assertTrue(sawRange[0]);assertEquals(4096,file.length());byte[] received=new byte[4096];FileInputStream in=new FileInputStream(file);try{assertEquals(4096,in.read(received));}finally{in.close();}assertArrayEquals(audio,received);}finally{server.stop(0);file.delete();}
    }}
    @Test public void changedValidatorCannotBeSpliced()throws Exception{final int[] calls={0};HttpFixture server=new HttpFixture(new InetSocketAddress("127.0.0.1",0));server.createContext("/",new HttpFixture.Handler(){public void handle(HttpFixture.Exchange e)throws IOException{calls[0]++;e.getResponseHeaders().set("ETag","\"new\"");e.getResponseHeaders().set("Content-Type","audio/mpeg");if(calls[0]==1){e.getResponseHeaders().set("Content-Range","bytes 16-31/32");e.sendResponseHeaders(206,16);e.getResponseBody().write(new byte[16]);}else {e.sendResponseHeaders(200,32);e.getResponseBody().write(new byte[32]);}}});server.start();File file=File.createTempFile("changed",".part");new FileOutputStream(file).write(new byte[16]);ResumableDownload.State state=new ResumableDownload.State();state.offset=16;state.total=32;state.validator="\"old\"";final URL url=new URL("http://127.0.0.1:"+server.getAddress().getPort()+"/");try{ResumableDownload.transfer(new ResumableDownload.Source(){public HttpURLConnection open()throws IOException{return (HttpURLConnection)url.openConnection();}},file,32,state,new ResumableDownload.Journal(){public void save(ResumableDownload.State s){}},null);assertEquals(2,calls[0]);assertEquals(32,file.length());assertEquals("\"new\"",state.validator);}finally{server.stop(0);file.delete();}}    @Test public void validatorsAndRangeBoundsRejectUnsafeValues()throws Exception{assertTrue(ResumableDownload.strong("\"opaque\""));assertFalse(ResumableDownload.strong("W/\"weak\""));assertFalse(ResumableDownload.strong("\"bad\r\nheader\""));for(String header:new String[]{"bytes 1-15/16","bytes 0-16/16","bytes 0-15/*","bytes 0-999999999999999999999999/16"})try{ResumableDownload.rangeTotal(header,0,16);fail("Invalid range accepted");}catch(IOException expected){}}
    @Test public void range416RestartsInsteadOfAppending()throws Exception{final int[] calls={0};HttpFixture server=new HttpFixture(new InetSocketAddress("127.0.0.1",0));server.createContext("/",new HttpFixture.Handler(){public void handle(HttpFixture.Exchange e)throws IOException{calls[0]++;e.getResponseHeaders().set("Content-Type","audio/mpeg");if(calls[0]==1)e.sendResponseHeaders(416,0);else{e.getResponseHeaders().set("ETag","\"new\"");e.sendResponseHeaders(200,32);e.getResponseBody().write(new byte[32]);}}});server.start();File file=File.createTempFile("unsatisfiable",".part");try{FileOutputStream out=new FileOutputStream(file);out.write(new byte[16]);out.close();ResumableDownload.State state=new ResumableDownload.State();state.offset=16;state.total=32;state.validator="\"old\"";final URL url=new URL("http://127.0.0.1:"+server.getAddress().getPort()+"/");ResumableDownload.transfer(new ResumableDownload.Source(){public HttpURLConnection open()throws IOException{return (HttpURLConnection)url.openConnection();}},file,32,state,new ResumableDownload.Journal(){public void save(ResumableDownload.State s){}},null);assertEquals(32,file.length());assertEquals(2,calls[0]);}finally{server.stop(0);file.delete();}}
    @Test public void journalFailureStillDisconnects()throws Exception{final boolean[] disconnected={false};File file=File.createTempFile("journal",".part");try{final HttpURLConnection connection=new HttpURLConnection(new URL("http://127.0.0.1")){public void connect(){}public boolean usingProxy(){return false;}public void disconnect(){disconnected[0]=true;}public int getResponseCode(){return 200;}public String getContentType(){return "audio/mpeg";}public int getContentLength(){return 32;}public InputStream getInputStream(){return new ByteArrayInputStream(new byte[32]);}};try{ResumableDownload.transfer(new ResumableDownload.Source(){public HttpURLConnection open(){return connection;}},file,32,new ResumableDownload.State(),new ResumableDownload.Journal(){public void save(ResumableDownload.State s)throws IOException{throw new IOException("Injected persistence failure");}},null);fail("Journal failure ignored");}catch(IOException expected){}assertTrue(disconnected[0]);}finally{file.delete();}}

}
