import io.onloopio.player.*;
import io.onloopio.model.Song;
import java.util.*;
import org.junit.Test;
import static org.junit.Assert.*;

public final class ReliabilityTest {
    private PlaybackQueue queue(int count,long seed){PlaybackQueue q=new PlaybackQueue(new Random(seed));List<PlaybackQueue.Entry> es=new ArrayList<PlaybackQueue.Entry>();for(int n=0;n<count;n++)es.add(new PlaybackQueue.Entry("entry"+n,"account",new Song(n%2==0?"A":"B","Title","Artist","Album","mp3",300)));q.replace(es,0);return q;}
    @Test public void finiteTraversalAndDuplicateOccurrences(){for(int count:new int[]{0,1,2,100})for(int seed=0;seed<100;seed++){PlaybackQueue q=queue(count,seed);q.configure(true,0);Set<String> seen=new HashSet<String>();while(q.current()!=null){assertTrue(seen.add(q.current().id));if(q.next(true)==null)break;}assertEquals(count,seen.size());assertNull(q.next(false));}}
    @Test public void historyAndRestore(){PlaybackQueue q=queue(100,19);q.configure(true,0);String first=q.current().id,second=q.next(true).id;assertEquals(first,q.previous().id);assertEquals(second,q.next(false).id);PlaybackQueue r=new PlaybackQueue(q.sessionId,new Random(900));r.restore(q.entries(),q.history(),q.pending(),q.cursor(),q.shuffle(),q.repeat());while(q.peek(true)!=null)assertEquals(q.next(true).id,r.next(true).id);assertNull(r.next(true));}
    @Test public void repeatAndEdits(){PlaybackQueue q=queue(2,0);q.configure(true,1);assertEquals("entry0",q.next(true).id);assertEquals("entry1",q.next(false).id);assertNull(q.next(false));q.configure(true,2);assertEquals("entry0",q.next(true).id);q.moveNext("entry1");assertEquals("entry1",q.next(false).id);assertEquals("entry0",q.remove("entry1").id);q.clearRemaining();assertEquals("entry0",q.current().id);}
    @Test public void playNextSurvivesShuffle(){PlaybackQueue q=queue(100,9);q.configure(true,0);q.moveNext("entry20");assertEquals("entry20",q.next(false).id);q.configure(false,0);assertEquals("entry1",q.peek(false).id);}
    @Test public void editsAfterRepeatedHistoryKeepPendingUnique(){PlaybackQueue q=queue(3,9);q.configure(false,2);for(int n=0;n<8;n++)q.next(false);for(int n=0;n<5;n++)q.previous();q.moveNext("entry2");assertEquals("entry2",q.peek(false).id);assertEquals(q.pending().size(),new HashSet<String>(q.pending()).size());PlaybackQueue r=new PlaybackQueue(new Random());r.restore(q.entries(),q.history(),q.pending(),q.cursor(),q.shuffle(),q.repeat());r.restoreForced(q.forcedCount());assertEquals(q.next(false).id,r.next(false).id);}
    @Test public void appendToEmptyCanBeSelected(){PlaybackQueue q=queue(0,1);q.append(Arrays.asList(new PlaybackQueue.Entry("first","account",new Song("A","A","A","A","mp3",60))),true);assertEquals("first",q.current().id);assertNull(q.next(false));}
    @Test public void qualificationAndBootBaseline(){assertEquals(Long.MAX_VALUE,ListeningSession.threshold(30000,2));assertEquals(15001,ListeningSession.threshold(30002,2));assertEquals(240000,ListeningSession.threshold(900000,2));ListeningSession s=new ListeningSession();s.restore(59000,false,2);s.baseline(0,100000);assertTrue(s.sample(1000,101000,120000,true));s.restore(s.playedMillis(),true,2);assertFalse(s.sample(20000,105000,120000,true));assertEquals(60000,s.playedMillis());}
    @Test public void tenThousandEntriesStayBounded(){PlaybackQueue q=queue(10000,17);q.configure(true,0);Set<String> seen=new HashSet<String>();for(int n=0;n<10000;n++){assertTrue(seen.add(q.current().id));if(n<9999)assertNotNull(q.next(false));}assertNull(q.next(false));assertEquals(10000,seen.size());try{q.append(Arrays.asList(new PlaybackQueue.Entry("overflow","account",new Song("A","A","A","A","mp3",60))),false);fail("Oversize queue accepted");}catch(IllegalArgumentException expected){}assertEquals(10000,q.entries().size());}
    @Test public void recoveryTerminatesEvenWithRepeat(){RecoveryPass pass=new RecoveryPass();assertTrue(pass.fail("occurrenceA"));assertTrue(pass.fail("occurrenceB"));assertFalse(pass.fail("occurrenceA"));pass.reset();assertFalse(pass.tried("occurrenceA"));}
    @Test public void wallClockChangesDoNotInventListeningTime(){long wall=1700000000000L;ListeningSession s=new ListeningSession();s.observeClock(wall,10000);s.baseline(10000,0);s.observeClock(wall+1000,11000);s.sample(11000,1000,600000,true);assertFalse(s.clockUncertain());assertEquals(1000,s.playedMillis());s.observeClock(wall-3600000,12000);assertTrue(s.clockUncertain());s.sample(12000,2000,600000,true);assertEquals(2000,s.playedMillis());ListeningSession restored=new ListeningSession();restored.restoreClock(s.clockWall(),s.clockElapsed(),s.clockUncertain());restored.observeClock(wall,100);assertTrue(restored.clockUncertain());s.reset();s.observeClock(0,0);assertTrue(s.clockUncertain());}
}
